### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by CPScript** [OnlineHacKing/PWD-WindowsRDP#1]
This is cool, but...

These links don't exist on the website:
How to use>> https://wwu.onlinehacking.org/pwd-windows-rdp-for-lifetime-free/
Gen Key>> https://wwu.onlinehacking.org/pwd-windows-key/

at least for me they don't...
![Screenshot 2023-03-01 8 14 46 AM](https://user-images.githubusercontent.com/83523587/222149481-7e855c47-23df-4360-9325-acdd71dab67e.png)

**Comment by CPScript** [comment]
Video example using a terminal:
[Screen recording 2023-03-01 8.17.12 AM.webm](https://user-images.githubusercontent.com/83523587/222150089-b9014055-c9ec-43f6-88fe-de4f9cdd9d46.webm)

**Comment by OnlineHacKing** [comment]
This not is not ready

**Comment by CPScript** [comment]
OK, I cant wait to see it in the future... also as an idea, you should make a Linux one (for people that "don't got access to it.")
